class ActionType: 
    ENCODE = 'encode'
    DECODE = 'decode'
    GET_ONE_CARD = 'get one card'
    GET_TWO_CARD = 'get two card'
    GET_THREE_CARD = 'get three card'
    GET_BEST_HAND = 'get best hand'
    ACKNOWLEDGMENT = "ack"
    SHUFFLE = "shuffle"
    TAKE_YOUR_HAND = "take your hand"
    TAKE_TABLE_CARDS = "take table cards"
    WINNER = "winner"
    RAISE = "raise"
    FOLD = "fold"
    CALL = "call"
    MAKE_BET = "make bet"
    IS_READY = "ready"
    NOT_READY = "not ready"
    ARE_YOU_READY = "are you ready"